### ISSUE TITLE
Best way to exclude tables from being pushed

### ISSUE THREAD

**Issue by stew978** [Azure/azure-mobile-apps#493] opened 2022-10-17 14:19 UTC
**Is your feature request related to a problem? Please describe.**
I'am using the DatasyncClient with offline tables.
I would wish that only specifics tables be Pushed to the server.
Is there any best practice to achieve this, without keeping excluded tables on the client sides as pending operation?

**Describe the solution you'd like**
I would like to have on option to pass a collection of tables to excludes for push action to the SyncContext.
On PushItems if the table is part of the tables to excludes, we could assume that the operation are not pending anymore.

**Comment by adrianhall** [comment] 2022-10-17 15:41
I get where you are coming from.  

There are two issues here, and I'd like to keep them separate.  
**Can you please remove the PULL parts of this issue and file them as a separate issue**

The PUSH operation is something that can be done on the client side.  You already have this ability.  First, the offline store has a method `GetTablesAsync()`, so you can get the list of tables easily.

```csharp
var tables = await store.GetTablesAsync();
var tablesToExclude = new string[] { "table1", "table2" };
var tablesToPush = tables.Except(tablesToExclude).ToList();
```

Now you can do the push easily:

```csharp
await client.PushTablesAsync(tablesToPush);
```

I can update the signature of PushOptions to include a "tablesToExclude" field, then thread this through the code, but it feels like overhead that isn't needed, especially since you can do everything in a very small piece of code.

**Comment by stew978** [comment] 2022-10-17 21:20
I did something similar to this, by passing directly the names of the tables I want to be pushed.
But I end up with the tables which are not pushed, still having pending operations.

**Comment by adrianhall** [comment] 2022-10-17 22:00
That would be expected.  You have made changes to those tables.  I'm not seeing what the issue is.

**Comment by stew978** [comment] 2022-10-18 09:14
There's no issue, as this is the expected behavior.

With previous version of the sdk we did a litle modification/hack to prevent the tables excluded from being pushed to stay with pending operations. 
We wanted our Api to have the main responsability of the work which as to be done when we push specifics tables, and then update the data that would be synced between every devices.

We did that by creating our custom MobileServiceSyncHandler
```c#
public class TableSyncHandler : IMobileServiceSyncHandler
```

and by defining our logic in the ExecuteTableOpearationAsync method as follow
```c#
public Task<JObject> ExecuteTableOperationAsync(IMobileServiceTableOperation operation)
{
     if (_excludedTables.Contains(operation.Table.TableName))
     {
          return Task.FromResult((JObject)null);
     }
     return operation.ExecuteAsync();
 }
```

This Handler was then passed to the SyncContext at the Initialization.

By doing this, we did get to dismiss the pending operations, on the tables that we didn't want to be pushed to the Api.

I was wondering if there was a way with the new version of the client, to achieve this.

**Comment by adrianhall** [comment] 2022-10-18 15:10
Just for my understanding, you want a table where new data is pulled from the API, but local changes are allowed to persist without being pushed?

**Comment by stew978** [comment] 2022-10-18 15:13
Yes, that's it.
Sorry if I wasn't clear in my explanation.

**Comment by adrianhall** [comment] 2022-10-28 21:15
Sorry for the delay here.  I'm struggling to decide if this is something we want to take in this library.  My current thinking is that it is something we don't want to do, so you should fork the project and do the adjustments yourself.  If I see folks +1 this idea, then I'll reconsider.

**Comment by adrianhall** [comment] 2022-12-12 21:56
After almost 2 months, no-one else has +1'ed this, so I am closing at this time.

**Closed by adrianhall** 2022-12-12 21:56 UTC
Labels: Feature Request, Client, .NET
